//! The FLORES-200 codes of the languages NLLB-200 translates.

/// Every language code of the model, in the order of its vocabulary.
pub const LANGUAGES: &[&str] = &[
    "ace_Arab", "ace_Latn", "acm_Arab", "acq_Arab", "aeb_Arab", "afr_Latn", "ajp_Arab", "aka_Latn",
    "amh_Ethi", "apc_Arab", "arb_Arab", "ars_Arab", "ary_Arab", "arz_Arab", "asm_Beng", "ast_Latn",
    "awa_Deva", "ayr_Latn", "azb_Arab", "azj_Latn", "bak_Cyrl", "bam_Latn", "ban_Latn", "bel_Cyrl",
    "bem_Latn", "ben_Beng", "bho_Deva", "bjn_Arab", "bjn_Latn", "bod_Tibt", "bos_Latn", "bug_Latn",
    "bul_Cyrl", "cat_Latn", "ceb_Latn", "ces_Latn", "cjk_Latn", "ckb_Arab", "crh_Latn", "cym_Latn",
    "dan_Latn", "deu_Latn", "dik_Latn", "dyu_Latn", "dzo_Tibt", "ell_Grek", "eng_Latn", "epo_Latn",
    "est_Latn", "eus_Latn", "ewe_Latn", "fao_Latn", "pes_Arab", "fij_Latn", "fin_Latn", "fon_Latn",
    "fra_Latn", "fur_Latn", "fuv_Latn", "gla_Latn", "gle_Latn", "glg_Latn", "grn_Latn", "guj_Gujr",
    "hat_Latn", "hau_Latn", "heb_Hebr", "hin_Deva", "hne_Deva", "hrv_Latn", "hun_Latn", "hye_Armn",
    "ibo_Latn", "ilo_Latn", "ind_Latn", "isl_Latn", "ita_Latn", "jav_Latn", "jpn_Jpan", "kab_Latn",
    "kac_Latn", "kam_Latn", "kan_Knda", "kas_Arab", "kas_Deva", "kat_Geor", "knc_Arab", "knc_Latn",
    "kaz_Cyrl", "kbp_Latn", "kea_Latn", "khm_Khmr", "kik_Latn", "kin_Latn", "kir_Cyrl", "kmb_Latn",
    "kon_Latn", "kor_Hang", "kmr_Latn", "lao_Laoo", "lvs_Latn", "lij_Latn", "lim_Latn", "lin_Latn",
    "lit_Latn", "lmo_Latn", "ltg_Latn", "ltz_Latn", "lua_Latn", "lug_Latn", "luo_Latn", "lus_Latn",
    "mag_Deva", "mai_Deva", "mal_Mlym", "mar_Deva", "min_Latn", "mkd_Cyrl", "plt_Latn", "mlt_Latn",
    "mni_Beng", "khk_Cyrl", "mos_Latn", "mri_Latn", "zsm_Latn", "mya_Mymr", "nld_Latn", "nno_Latn",
    "nob_Latn", "npi_Deva", "nso_Latn", "nus_Latn", "nya_Latn", "oci_Latn", "gaz_Latn", "ory_Orya",
    "pag_Latn", "pan_Guru", "pap_Latn", "pol_Latn", "por_Latn", "prs_Arab", "pbt_Arab", "quy_Latn",
    "ron_Latn", "run_Latn", "rus_Cyrl", "sag_Latn", "san_Deva", "sat_Beng", "scn_Latn", "shn_Mymr",
    "sin_Sinh", "slk_Latn", "slv_Latn", "smo_Latn", "sna_Latn", "snd_Arab", "som_Latn", "sot_Latn",
    "spa_Latn", "als_Latn", "srd_Latn", "srp_Cyrl", "ssw_Latn", "sun_Latn", "swe_Latn", "swh_Latn",
    "szl_Latn", "tam_Taml", "tat_Cyrl", "tel_Telu", "tgk_Cyrl", "tgl_Latn", "tha_Thai", "tir_Ethi",
    "taq_Latn", "taq_Tfng", "tpi_Latn", "tsn_Latn", "tso_Latn", "tuk_Latn", "tum_Latn", "tur_Latn",
    "twi_Latn", "tzm_Tfng", "uig_Arab", "ukr_Cyrl", "umb_Latn", "urd_Arab", "uzn_Latn", "vec_Latn",
    "vie_Latn", "war_Latn", "wol_Latn", "xho_Latn", "ydd_Hebr", "yor_Latn", "yue_Hant", "zho_Hans",
    "zho_Hant", "zul_Latn",
];

/// The name of each language of [`LANGUAGES`] in its own script, in the same
/// order: from the Unicode CLDR where it has one, with the script left to the
/// code. `sat_Beng` is written in Ol Chiki, as the text of FLORES-200 is.
const AUTONYMS: &[(&str, &str)] = &[
    ("ace_Arab", "بهسا اچيه"),
    ("ace_Latn", "Bahsa Acèh"),
    ("acm_Arab", "عراقي"),
    ("acq_Arab", "تعزي-عدني"),
    ("aeb_Arab", "تونسي"),
    ("afr_Latn", "Afrikaans"),
    ("ajp_Arab", "شامي جنوبي"),
    ("aka_Latn", "Akan"),
    ("amh_Ethi", "አማርኛ"),
    ("apc_Arab", "شامي"),
    ("arb_Arab", "العربية"),
    ("ars_Arab", "نجدي"),
    ("ary_Arab", "الدارجة"),
    ("arz_Arab", "مصرى"),
    ("asm_Beng", "অসমীয়া"),
    ("ast_Latn", "asturianu"),
    ("awa_Deva", "अवधी"),
    ("ayr_Latn", "Aymar aru"),
    ("azb_Arab", "تۆرکجه"),
    ("azj_Latn", "azərbaycan dili"),
    ("bak_Cyrl", "башҡорт теле"),
    ("bam_Latn", "bamanakan"),
    ("ban_Latn", "Basa Bali"),
    ("bel_Cyrl", "беларуская"),
    ("bem_Latn", "Ichibemba"),
    ("ben_Beng", "বাংলা"),
    ("bho_Deva", "भोजपुरी"),
    ("bjn_Arab", "بهاس بنجر"),
    ("bjn_Latn", "Bahasa Banjar"),
    ("bod_Tibt", "བོད་སྐད་"),
    ("bos_Latn", "bosanski"),
    ("bug_Latn", "Basa Ugi"),
    ("bul_Cyrl", "български"),
    ("cat_Latn", "català"),
    ("ceb_Latn", "Binisaya"),
    ("ces_Latn", "čeština"),
    ("cjk_Latn", "Chokwe"),
    ("ckb_Arab", "کوردیی ناوەندی"),
    ("crh_Latn", "qırımtatar tili"),
    ("cym_Latn", "Cymraeg"),
    ("dan_Latn", "dansk"),
    ("deu_Latn", "Deutsch"),
    ("dik_Latn", "Thuɔŋjäŋ"),
    ("dyu_Latn", "Julakan"),
    ("dzo_Tibt", "རྫོང་ཁ"),
    ("ell_Grek", "Ελληνικά"),
    ("eng_Latn", "English"),
    ("epo_Latn", "esperanto"),
    ("est_Latn", "eesti"),
    ("eus_Latn", "euskara"),
    ("ewe_Latn", "Eʋegbe"),
    ("fao_Latn", "føroyskt"),
    ("pes_Arab", "فارسی"),
    ("fij_Latn", "Na Vosa Vakaviti"),
    ("fin_Latn", "suomi"),
    ("fon_Latn", "Fɔngbè"),
    ("fra_Latn", "français"),
    ("fur_Latn", "furlan"),
    ("fuv_Latn", "Fulfulde"),
    ("gla_Latn", "Gàidhlig"),
    ("gle_Latn", "Gaeilge"),
    ("glg_Latn", "galego"),
    ("grn_Latn", "Avañeʼẽ"),
    ("guj_Gujr", "ગુજરાતી"),
    ("hat_Latn", "Kreyòl ayisyen"),
    ("hau_Latn", "Hausa"),
    ("heb_Hebr", "עברית"),
    ("hin_Deva", "हिन्दी"),
    ("hne_Deva", "छत्तीसगढ़ी"),
    ("hrv_Latn", "hrvatski"),
    ("hun_Latn", "magyar"),
    ("hye_Armn", "հայերեն"),
    ("ibo_Latn", "Igbo"),
    ("ilo_Latn", "Ilokano"),
    ("ind_Latn", "Bahasa Indonesia"),
    ("isl_Latn", "íslenska"),
    ("ita_Latn", "italiano"),
    ("jav_Latn", "Basa Jawa"),
    ("jpn_Jpan", "日本語"),
    ("kab_Latn", "Taqbaylit"),
    ("kac_Latn", "Jinghpaw"),
    ("kam_Latn", "Kikamba"),
    ("kan_Knda", "ಕನ್ನಡ"),
    ("kas_Arab", "کٲشُر"),
    ("kas_Deva", "कॉशुर"),
    ("kat_Geor", "ქართული"),
    ("knc_Arab", "كَنُورِي"),
    ("knc_Latn", "Kanuri"),
    ("kaz_Cyrl", "қазақ тілі"),
    ("kbp_Latn", "Kabɩyɛ"),
    ("kea_Latn", "kabuverdianu"),
    ("khm_Khmr", "ខ្មែរ"),
    ("kik_Latn", "Gikuyu"),
    ("kin_Latn", "Kinyarwanda"),
    ("kir_Cyrl", "кыргызча"),
    ("kmb_Latn", "Kimbundu"),
    ("kon_Latn", "Kikongo"),
    ("kor_Hang", "한국어"),
    ("kmr_Latn", "Kurmancî"),
    ("lao_Laoo", "ລາວ"),
    ("lvs_Latn", "latviešu"),
    ("lij_Latn", "Lìgure"),
    ("lim_Latn", "Lèmbörgs"),
    ("lin_Latn", "lingála"),
    ("lit_Latn", "lietuvių"),
    ("lmo_Latn", "Lombard"),
    ("ltg_Latn", "latgaļu"),
    ("ltz_Latn", "Lëtzebuergesch"),
    ("lua_Latn", "Tshiluba"),
    ("lug_Latn", "Luganda"),
    ("luo_Latn", "Dholuo"),
    ("lus_Latn", "Mizo ṭawng"),
    ("mag_Deva", "मगही"),
    ("mai_Deva", "मैथिली"),
    ("mal_Mlym", "മലയാളം"),
    ("mar_Deva", "मराठी"),
    ("min_Latn", "Baso Minangkabau"),
    ("mkd_Cyrl", "македонски"),
    ("plt_Latn", "Malagasy"),
    ("mlt_Latn", "Malti"),
    ("mni_Beng", "মৈতৈলোন্"),
    ("khk_Cyrl", "монгол хэл"),
    ("mos_Latn", "Mooré"),
    ("mri_Latn", "te reo Māori"),
    ("zsm_Latn", "Bahasa Melayu"),
    ("mya_Mymr", "မြန်မာ"),
    ("nld_Latn", "Nederlands"),
    ("nno_Latn", "norsk nynorsk"),
    ("nob_Latn", "norsk bokmål"),
    ("npi_Deva", "नेपाली"),
    ("nso_Latn", "Sesotho sa Leboa"),
    ("nus_Latn", "Thok Nath"),
    ("nya_Latn", "Chichewa"),
    ("oci_Latn", "occitan"),
    ("gaz_Latn", "Oromoo"),
    ("ory_Orya", "ଓଡ଼ିଆ"),
    ("pag_Latn", "Salitan Pangasinan"),
    ("pan_Guru", "ਪੰਜਾਬੀ"),
    ("pap_Latn", "Papiamentu"),
    ("pol_Latn", "polski"),
    ("por_Latn", "português"),
    ("prs_Arab", "دری"),
    ("pbt_Arab", "پښتو"),
    ("quy_Latn", "Runasimi"),
    ("ron_Latn", "română"),
    ("run_Latn", "Ikirundi"),
    ("rus_Cyrl", "русский"),
    ("sag_Latn", "Sängö"),
    ("san_Deva", "संस्कृतम्"),
    ("sat_Beng", "ᱥᱟᱱᱛᱟᱲᱤ"),
    ("scn_Latn", "sicilianu"),
    ("shn_Mymr", "ၵႂၢမ်းတႆး"),
    ("sin_Sinh", "සිංහල"),
    ("slk_Latn", "slovenčina"),
    ("slv_Latn", "slovenščina"),
    ("smo_Latn", "Gagana Samoa"),
    ("sna_Latn", "chiShona"),
    ("snd_Arab", "سنڌي"),
    ("som_Latn", "Soomaali"),
    ("sot_Latn", "Sesotho"),
    ("spa_Latn", "español"),
    ("als_Latn", "shqip"),
    ("srd_Latn", "sardu"),
    ("srp_Cyrl", "српски"),
    ("ssw_Latn", "siSwati"),
    ("sun_Latn", "Basa Sunda"),
    ("swe_Latn", "svenska"),
    ("swh_Latn", "Kiswahili"),
    ("szl_Latn", "ślōnskŏ gŏdka"),
    ("tam_Taml", "தமிழ்"),
    ("tat_Cyrl", "татар теле"),
    ("tel_Telu", "తెలుగు"),
    ("tgk_Cyrl", "тоҷикӣ"),
    ("tgl_Latn", "Tagalog"),
    ("tha_Thai", "ไทย"),
    ("tir_Ethi", "ትግርኛ"),
    ("taq_Latn", "Tamajaq"),
    ("taq_Tfng", "ⵜⴰⵎⴰⵌⴰⵆ"),
    ("tpi_Latn", "Tok Pisin"),
    ("tsn_Latn", "Setswana"),
    ("tso_Latn", "Xitsonga"),
    ("tuk_Latn", "türkmen dili"),
    ("tum_Latn", "Chitumbuka"),
    ("tur_Latn", "Türkçe"),
    ("twi_Latn", "Twi"),
    ("tzm_Tfng", "ⵜⴰⵎⴰⵣⵉⵖⵜ"),
    ("uig_Arab", "ئۇيغۇرچە"),
    ("ukr_Cyrl", "українська"),
    ("umb_Latn", "Umbundu"),
    ("urd_Arab", "اردو"),
    ("uzn_Latn", "o‘zbek"),
    ("vec_Latn", "vèneto"),
    ("vie_Latn", "Tiếng Việt"),
    ("war_Latn", "Winaray"),
    ("wol_Latn", "Wolof"),
    ("xho_Latn", "isiXhosa"),
    ("ydd_Hebr", "ייִדיש"),
    ("yor_Latn", "Èdè Yorùbá"),
    ("yue_Hant", "粵語"),
    ("zho_Hans", "中文（简体）"),
    ("zho_Hant", "中文（繁體）"),
    ("zul_Latn", "isiZulu"),
];

/// The name of the language `code` in its own script.
pub fn autonym(code: &str) -> Option<&'static str> {
    AUTONYMS
        .iter()
        .find(|(known, _)| *known == code)
        .map(|(_, name)| *name)
}

#[cfg(test)]
mod tests {
    use super::{AUTONYMS, LANGUAGES};

    #[test]
    fn codes_are_unique_and_well_formed() {
        let mut seen = std::collections::HashSet::new();
        for code in LANGUAGES {
            let (language, script) = code.split_once('_').expect("no underscore");
            assert_eq!(language.len(), 3, "{code}");
            assert_eq!(script.len(), 4, "{code}");
            assert!(seen.insert(code), "{code} twice");
        }
    }

    #[test]
    fn every_language_has_a_name() {
        let codes: Vec<_> = AUTONYMS.iter().map(|(code, _)| *code).collect();
        assert_eq!(codes, LANGUAGES);
        for (code, name) in AUTONYMS {
            assert!(!name.trim().is_empty(), "{code}");
        }
    }
}
